/**
 * Fork from https://github.com/wkrueger/redutser
 */

import produce from "immer";

export const META = Symbol("META");

type SecondArg<T> = T extends (x: any, y: infer V) => any ? V : never;
type Values<K> = K[keyof K];

export type Reducer<State, Payload = any> = (s: State, p: Payload) => State;

export interface ReducerDict<State> {
    [name: string]: (this: ReducerDict<State>, s: State, p: any) => State;
}

export type ActionCreatorsFromReducerDict<Inp extends ReducerDict<any>> = {
    [K in keyof Inp]: (
        payload: SecondArg<Inp[K]>,
    ) => {type: K; payload: SecondArg<Inp[K]>}
};

export type ActionTypesFromReducerDict<
    Inp extends ReducerDict<any>
> = ReturnType<Values<ActionCreatorsFromReducerDict<Inp>>>;

export const createSimpleActions = <State, Dict extends ReducerDict<State>>(
    initialState: State,
    reducerDict: Dict,
) => {
    const creators = actionCreatorsFromReducerDict()(reducerDict);

    return Object.assign(creators, {
        [META]: {
            initialState,
            reducerDict,
        },
    });
};

function actionCreatorsFromReducerDict() {
    return <D extends ReducerDict<any>>(
        dict: D,
    ): ActionCreatorsFromReducerDict<D> => {
        return Object.keys(dict).reduce(
            (out, name) => ({
                ...out,
                [name]: (i: any) => ({type: name, payload: i}),
            }),
            {},
        ) as any;
    };
}

/**
 * Get the reducer function from the actions generated by createSimpleActions
 */
export function createReducer<State, Dict extends ReducerDict<State>>(actions: {
    [META]: {initialState: State; reducerDict: Dict};
}) {
    const meta = actions[META];

    return function reducer(
        state = meta.initialState,
        action: ActionTypesFromReducerDict<Dict>,
    ): State {
        if (meta.reducerDict[action.type]) {
            return produce(state, draftState => {
                return meta.reducerDict[action.type](
                    draftState,
                    action.payload,
                );
            });
        }
        return state;
    };
}
